javafx:
  title: SmartJavaFx
  appicons: /icon/icon.png
  stage:
    width: 470
    height: 990
#    style: DECORATED  # javafx.stage.StageStyle [DECORATED, UNDECORATED, TRANSPARENT, UTILITY, UNIFIED]
    resizable: false

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/syj_bjl?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 40
      connection-timeout: 60000
      minimum-idle: 10
      idle-timeout: 60000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      generate_statistics: true
      jdbc:
        batch_size: 500
        batch_versioned_data: true
      order_inserts: true
      order_updates: true
      ddl-auto: update
    show-sql: false
    database: mysql
